# config/_default/menus.toml

[[main]]
  name = "posts"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

#[[main]]
#  pre = "github"
#  name = "GitHub"
#  url = "https://github.com/nunocoracao/blowfish"
#  weight = 30

#[[main]]
#  identifier = "github2"
#  pre = "github"
#  url = "https://github.com/nunocoracao/blowfish"
#  weight = 40

[[footer]]
  name = "Privacy"
  url = "https://external-link"
